package com.framgia.model;
// Generated Feb 27, 2017 3:44:10 PM by Hibernate Tools 5.2.0.CR1

/**
 * OrderDetail generated by hbm2java
 */
public class OrderDetail implements java.io.Serializable {

	private int orderId;
	private Order order;
	private Product product;
	private Shop shop;
	private Integer quantity;
	private Integer status;

	public OrderDetail() {
	}

	public OrderDetail(Order order, Product product, Shop shop) {
		this.order = order;
		this.product = product;
		this.shop = shop;
	}

	public OrderDetail(Order order, Product product, Shop shop, Integer quantity, Integer status) {
		this.order = order;
		this.product = product;
		this.shop = shop;
		this.quantity = quantity;
		this.status = status;
	}

	public int getOrderId() {
		return this.orderId;
	}

	public void setOrderId(int orderId) {
		this.orderId = orderId;
	}

	public Order getOrder() {
		return this.order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Product getProduct() {
		return this.product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public Shop getShop() {
		return this.shop;
	}

	public void setShop(Shop shop) {
		this.shop = shop;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
