package com.framgia.model;
// Generated Feb 27, 2017 3:44:10 PM by Hibernate Tools 5.2.0.CR1

import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * Shop generated by hbm2java
 */
public class Shop implements java.io.Serializable {

	private Integer id;
	private String name;
	private String address;
	private String tel;
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getTel() {
		return tel;
	}
	public void setTel(String tel) {
		this.tel = tel;
	}
	public Shop(Integer id, String name, String address, String tel) {
		super();
		this.id = id;
		this.name = name;
		this.address = address;
		this.tel = tel;
	}
	public Shop() {
		super();
	}
	
	public Shop(Integer id){
		this.id = id;
	}

}
